name: Github Actions

on:
  pull_request:
    branches:
      - master

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"

    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        experimental: [true]
        php-version:
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: "cs2pr,composer:v2"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.json') }}"

      - name: "Install dependencies with composer"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Run squizlabs/php_codesniffer"
        run: "composer code-style"

  phpunit:
    name: "PHPUnit tests"

    runs-on: "ubuntu-latest"

    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        experimental: [true]
        php-version:
          - "7.4"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          tools: "composer:v2"

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.json') }}"

      - name: "Install dependencies with composer"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Tests"
        run: "composer tests"

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
